{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}

package:
  name: {{ pyproject["project"]["name"] }}
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../

build:
  noarch: python
  preserve_egg_dir: True
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    {% for dep in pyproject["build-system"]["requires"] %}
    - {{ dep.lower() }}
    {% endfor %}

  run:
    - python {{ pyproject["project"]["requires-python"] }}
    {% for dep in pyproject["project"]["dependencies"] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  requires:
    - pytest
  imports:
    - {{ pyproject["project"]["name"] }}
  source_files:
    - test/test_*.py
  commands:
   - cd test
   - pytest -v

about:
#  home: {{ home }}
  license: CeCILL_C
#  summary: {{ description }}

