{% set version = "2.0.0" %}

package:
  name: alinea.astk
  version: {{ version }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - openalea.core
    - numpy
    - pandas
    - openalea.plantgl
    - pvlib
    - alinea.caribu

test:
  imports:
    - openalea.mtg

about:
  home: http://openalea.gforge.inria.fr/
  license: CeCILL_C
  summary: OpenAlea.MTG implements Multiscale Tree Graph datastructure and interfaces

