{% set data = load_setup_py_data() %}

package:
  name: alinea.astk
  version: {{ data.get('version') }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python {{PY_VER}}
    - setuptools
    - numpy=1.20|>=1.21.5

  run:
    - python {{PY_VER}}
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - openalea.plantgl
    - alinea.caribu
    - pvlib-python<0.9.0
    - six

test:
  requires:
    - pytest
  imports:
    - alinea.astk
  source_files:
    - test/test_*.py
  commands:
   - cd test
   - pytest -v

about:
  home: http://github.com/openalea-incubator/astk
  license: CeCILL_C
  summary: The Alinea.astk package provides utilities for simulation of FSPM models.

