# This file has been automatically generated by pkg_builder

from openalea.core import *

__name__ = 'alinea.astk'
__version__ = '1.0.0'
__license__ = 'CeCILL-C'
__author__ = None
__institutes__ = None
__description__ = ''
__url__ = 'http://openalea.gforge.inria.fr'

__editable__ = 'True'
__icon__ = ''
__alias__ = []

__all__ = []

astk_TimeControl = Factory(name='TimeControl',
                nodemodule='alinea.astk.TimeControl',
                nodeclass='TimeControl',
                inputs=[{'interface': IInt, 'name': 'delay', 'value': 1, 'desc': ''},
                        {'interface': IInt, 'name': 'steps', 'value': 2, 'desc': ''},
                        {'interface': None, 'name': 'model', 'value': None, 'desc': ''},
                        {'interface': None, 'name': 'weather', 'value': None, 'desc': ''},
                        {'interface': IStr, 'name': 'start_date', 'value': None, 'desc': ''}],
               )
__all__.append('astk_TimeControl')


    
